[package]
name = "wallet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "^0.8.5"
getrandom = "0.2.10"
secp256k1 = { version = "0.28.0", features = ["rand-std"] }
